require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: enable

# vim: sw=2 sts=2 ts=8 et:
