cache: bundler
language: ruby
sudo: false

os:
  - osx
  - linux

rvm:
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem update --system
  - gem install bundler

deploy:
  skip_cleanup: true
  provider: script
  script: 'gem update --system && gem install bundler && bundle exec rake coveralls:push'
  on:
    branch: master
    condition: $TRAVIS_RUBY_VERSION = 2.6 && $TRAVIS_OS_NAME = linux
