cache: bundler
language: ruby
sudo: false

os:
  - osx
  - linux

rvm:
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem update --system
  - gem install bundler

after_success: |
  if [[ "$TRAVIS_RUBY_VERSION" = 2.6 && "$TRAVIS_OS_NAME" = linux ]]; then
    bundle exec rake coveralls:push
  fi
